# The yaml constructors are ignored, but I will get to fixing them
routes:
    '/,/index.html':
        # show the table ui
        # demo data is loaded as a pandas dataframe
        # start with demo data and paste new data later
        function: show_table
        methods: [get]
    '/keys':
        function: keys
        methods: [get]
    '/bokeh':
        # create bokeh data to display on the page
        # should return bokeh json
        function: bokeh_data
        methods: [post]
    '/dataframe':
        # return pandas dataframe as html
        function: dataframe_html
        methods: [get,post]
    '/data/<path:data_key>/':
        function: show_dataframe
        methods: [get,post]
